### ISSUE TITLE
Produce color from hash

### ISSUE THREAD

**Issue by bologer** [mistic100/RandomColor.php#14]
I would like to use your library to produce color from hash string?

For example,  I have pie chart and I would like to assign color per each portion of it based on data for such portion. 

I would like to hash within that portion and produce some color based on that hash. 

Now I am facing problem that it always generates different color.

**Comment by mistic100** [comment]
See this for example https://github.com/mistic100/RandomColor.php/pull/5#issuecomment-196353517

don't forget to reset mt_srand or will likely compromise the security of your app.

**Comment by mistic100** [comment]
This PR explains why I don't want to https://github.com/mistic100/RandomColor.php/pull/5
