### ISSUE TITLE
New functionality: not retrive similar colors

### ISSUE THREAD

**Issue by Axel-AMGHAR** [mistic100/RandomColor.php#18]
Hello,

When we use RandomColor::many(36);
We often get similar colors.
eg green, and darker green.

It could be useful to not retrive similar colors.

Let me know what you think. And if it's doable.

**Comment by mistic100** [comment]
What would be the criteria ? For 36 colors I think you will never have something satisfaying, you'd beter generate yourself and rainbow and shuffle the colors.
