### ISSUE TITLE
Deterministic Color Creation

### ISSUE THREAD

**Issue by tpetry** [mistic100/RandomColor.php#2]
It would be nice to have the option to create deterministic colors. Providing a seed for RandomColor (which will not interfere with the normal mt_random) would be really nice.

**Comment by mistic100** [comment]
You can already provide a custom Pseudo Random Generator with the `prng` option.
I think it's enough.

I did this because we CANNOT not interfere with mt_rand when setting the seed. Now it's up to the user to do it like he wants and the lib can't be charged for alteration and generator.

**Comment by tpetry** [comment]
Ah, you're right. But v.1.0.1 which has this feature is not available for composer installations [1], therefore i was unaware of this feature. And can't actually don't use it because of a strict only-tagged-composer-releases policy :(

[1] https://packagist.org/packages/mistic100/randomcolor

**Comment by mistic100** [comment]
Updated, would have been cool if Packgist didn't bitch when composer.json version mismatch with the git tag.

**Comment by tpetry** [comment]
Thanks. Very fast support :)
